### PR TITLE
Sign in and sign out fixes

### LINKED ISSUE #106: Sign in / sign out
- [ ] Make the enter key work for the sign in button
- [ ] Connect sign out functionality to the sign out button in the navbar dropdown(s)

### PR DESCRIPTION
**Pull request by ctc-devops**
- [x] Make the enter key work for the sign in button
- [x] Connect sign out functionality to the sign out button in the navbar dropdown(s)

Also styled forgot password 

closes #106

### CODE REVIEW

File: src/common/auth_errors.js [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+    'The request does not contain a valid proof of first factor successful sign-in.',
+  'invalid-oauth-provider':
+    'EmailAuthProvider is not supported for this operation. This operation only supports OAuth providers.',
+  'invalid-oauth-client-id':
+    'The OAuth client ID provided is either invalid or does not match the specified API key.',
+  'unauthorized-domain':
+    'This domain is not authorized for OAuth operations for your Firebase project. Edit the list of authorized domains from the Firebase console.',
+  'invalid-action-code':
+    'The action code is invalid. This can happen if the code is malformed, expired, or has already been used.',
+  'wrong-password': 'The password is incorrect.',
```
Comment (ctc-devops) [inline src/common/auth_errors.js:56]: 🚫 **[detect-secrets]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>
* Secret Keyword

File: src/common/auth_errors.js [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+    'The current environment does not support the specified persistence type.',
+  'unsupported-tenant-operation': 'This operation is not supported in a multi-tenant context.',
+  'unverified-email': 'The operation requires a verified email.',
+  'user-cancelled': 'The user did not grant your application the permissions it requested.',
+  'user-not-found':
+    'There is no user record corresponding to this identifier. The user may have been deleted.',
+  'user-disabled': 'The user account has been disabled by an administrator.',
+  'user-mismatch': 'The supplied credentials do not correspond to the previously signed in user.',
+  'user-signed-out': '',
+  'weak-password': 'The password must be 6 characters long or more.',
```
Comment (ctc-devops) [inline src/common/auth_errors.js:135]: 🚫 **[detect-secrets]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>
* Secret Keyword

**Comment by janehvo** [comment]
need to refactor frontend component then done

File: src/components/Authentication/ForgotPassword.jsx [hunk 3]
```diff
@@ -1,42 +1,74 @@
+import { Box, Container, Center, Text, Flex, Heading, Input, Button } from '@chakra-ui/react';
```
Comment (ctc-devops) [inline src/components/Authentication/ForgotPassword.jsx]: ⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Center' is defined but never used.

File: src/components/Authentication/Login.jsx [hunk 4]
```diff
@@ -12,11 +12,15 @@ import {
   Button,
   Flex,
   Link,
+  Text,
   Center,
+  Container,
+  Stack,
```
Comment (ctc-devops) [inline src/components/Authentication/Login.jsx:18]: ⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Stack' is defined but never used.

**Review by ctian1 — APPROVED** [review]
